
t1:
    path: Data_MiseEnForme/Data_MiseEnForme/IRM/Brain/t1.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

    snr:
        white_matter:
            fg: [77, 97, 88]
            bg: [166, 222, 88]
            window_size: 10
        gray_matter:
            fg: [30, 97, 88]
            bg: [166, 222, 88]
            window_size: 10
        white_matter/ventricle:
          fg: [ 77, 97, 88 ]
          bg: [ 83, 104, 101 ] # Ventricle
          window_size: 10
        gray_matter/ventricle:
          fg: [ 30, 97, 88 ]
          bg: [ 83, 104, 101 ] # Ventricle
          window_size: 10

    filter:
         gaussian:
            sigma: 1
         nlmeans:
            patch_radius: 1
            block_radius: 5
            rician: True
            mask_value: 20
         anisotropic_diffusion:
             niter: 1
             kappa: 50
             gamma: 0.1


flair:
    path: Data_MiseEnForme/Data_MiseEnForme/IRM/Brain/flair.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

    snr:
        white_matter:
            fg: [67, 55, 11]
            bg: [19, 231, 11]
            window_size: 10
        gray_matter:
            fg: [46, 55, 11]
            bg: [19, 231, 11]
            window_size: 10
        white_matter/ventricle:
          fg: [67, 55, 11]
          bg: [ 92, 134, 11 ] # Ventricle
          window_size: 10
        gray_matter/ventricle:
          fg: [46, 55, 11]
          bg: [ 92, 134, 11 ] # Ventricle
          window_size: 10

    filter:
         gaussian:
            sigma: 0.65
         nlmeans:
            mask_value: 25
            patch_radius: 1
            block_radius: 5
            rician: True
         anisotropic_diffusion:
             niter: 3
             kappa: 50
             gamma: 0.1

heart:
    path: Data_MiseEnForme/Data_MiseEnForme/IRM/Heart/PetitAxe/Slice06.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

CT:
    path: Data_MiseEnForme/Data_MiseEnForme/CT/rat111.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

US:
    path: Data_MiseEnForme/Data_MiseEnForme/Ultrasound/us.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True
