
t1:
    path: Data_MiseEnForme/Data_MiseEnForme/IRM/Brain/t1.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

    snr:
        white_matter:
            fg: [77, 97, 88]
            bg: [166, 222, 88]
            window_size: 10
        gray_matter:
            fg: [30, 97, 88]
            bg: [166, 222, 88]
            window_size: 10

    filter:
         gaussian:
            sigma: 0.65
         nlmeans:
            patch_radius: 1
            block_radius: 1
            rician: True
            mask_value: 20
         anisotropic_diffusion: {} # use defaults


flair:
    path: Data_MiseEnForme/Data_MiseEnForme/IRM/Brain/flair.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

    snr:
        white_matter:
            fg: [67, 55, 11]
            bg: [19, 231, 11]
            window_size: 10
        gray_matter:
            fg: [46, 55, 11]
            bg: [19, 231, 11]
            window_size: 10

    filter:
         gaussian:
            sigma: 0.65
         nlmeans:
            mask_value: 20
            patch_radius: 1
            block_radius: 1
            rician: True
         anisotropic_diffusion: {} # use defaults


heart:
    path: Data_MiseEnForme/Data_MiseEnForme/IRM/Heart/PetitAxe/Slice06.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

   # snr:
    #    white_matter:
    #        fg: [169, 185, 7,10]    #y,x,z
   #         bg: [69, 13, 7,100]
    #        window_size: 10
    #    gray_matter:
    #        fg: [83, 138, 7,10]
    #        bg: [69, 13, 7,100]
    #        window_size: 10

    filter:
         gaussian:
            sigma: 0.65
         nlmeans:
            mask_value: 20
            patch_radius: 1
            block_radius: 1
            rician: True
         anisotropic_diffusion: {} # use defaults


CT:
    path: Data_MiseEnForme/Data_MiseEnForme/CT/rat111.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True

   # snr:
    #    white_matter:
    #        fg: [257, 223, 266]    #y,x,z
    #        bg: [336, 26, 266]
     #       window_size: 10
     #   gray_matter:
     #       fg: [120, 85, 266]
     #       bg: [336, 26, 266]
     #       window_size: 10
        
    filter:
         gaussian:
            sigma: 0.65
         nlmeans:
            mask_value: 20
            patch_radius: 1
            block_radius: 1
            rician: True
         anisotropic_diffusion: {} # use defaults

US:
    path: Data_MiseEnForme/Data_MiseEnForme/Ultrasound/us.nii
    view_kwargs:
        aspect: null
        cmap: 'gray'
        rotate: True
  #  snr:
 #      white_matter:
  #          fg: [216, 254, 185]    #y,x,z
  #          bg: [45, 32, 185]
   #         window_size: 10
   #     gray_matter:
   #         fg: [283, 151, 185]
   #         bg: [45, 32, 185]
   #         window_size: 10
        
    filter:
         gaussian:
            sigma: 0.65
         nlmeans:
            mask_value: 20
            patch_radius: 1
            block_radius: 1
            rician: True
         anisotropic_diffusion: {} # use defaults
